In [15]:
# Problem 1

import numpy0

ModuleNotFoundError: No module named 'numpy0'

In [16]:
try:
    import numpy0
except ModuleNotFoundError:
    print("Sorry, module not found.")

Sorry, module not found.


In [17]:
# Problem 2

def div(x,y):
    assert y != 0, 'Can’t divide'
    return x/y

In [18]:
div(10,0)

AssertionError: Can’t divide

In [46]:
# Problem 3

def example_func(my_list: list):
    
    try:
        if (type(my_list) != list):
            raise Exception("value type is not list")
        else:
            my_sum = 0
            sum_of_pairs = []
            
            for i in range(len(my_list)):
                if i+1 > len(my_list):
                    raise Exception("list index out of range")
                sum_of_pairs.append(my_list[i] + my_list[i+1])
                
            print("sumOfPairs = ", sum_of_pairs)
    
    except Exception as e:
        print(e)

In [47]:
example_func(1)

value type is not list


In [48]:
example_func([1,2,3,4,5])

list index out of range


In [80]:
# Problem 4

def UpperContent(fileName):
    
    try:
        myfile = open(fileName, "r")
        for line in myfile:
            print(line.upper())
        myfile.close()
    except FileNotFoundError:
        print('Sorry, this file does not exist')

In [81]:
UpperContent('file.txt')

HELLO WORLD!


In [82]:
UpperContent('file1.txt')

Sorry, this file does not exist


In [61]:
# Problem 5

import numpy as np

x = np.random.randint(1, 10, (3,5))
print(x)

[[6 9 1 9 2]
 [2 2 1 7 2]
 [9 4 6 6 9]]


In [63]:
# Problem 6

x = np.zeros(10)
x[4] = 3
print(x)

[0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]


In [64]:
# Problem 7

x = np.arange(3,15)
print(x)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [66]:
# Problem 8

x = np.array([1, 3, 5, 2, 4, 5])
y = x.reshape(3,2)
z = x.reshape(2,3)
print(y, '\n')
print(z)

[[1 3]
 [5 2]
 [4 5]] 

[[1 3 5]
 [2 4 5]]


In [67]:
# Problem 9 <=> Numpy_exercises 20

def my_func(x):
    mean  = x.mean()
    while mean > 5:
        x = x/2
        mean = x.mean()
    else:
        print(x)

In [68]:
my_func(np.array([64,8,16]))

[8. 1. 2.]


In [69]:
# Problem 10 <=> Numpy_exercises 21

def func_column(x):
    print(x[...,0])
    print(x[...,1])
    print(x[...,2])
    print(x[...,3])
    
def func_row(x):
    print(x[0,...])
    print(x[1,...])
    print(x[1,...])
    print(x[3,...])
    print(x[4,...])

In [70]:
x = np.random.randint(1, 10, 20).reshape(5,4)
print(x)

[[1 5 9 6]
 [9 4 9 4]
 [4 3 6 1]
 [6 3 5 4]
 [3 3 9 4]]


In [71]:
func_column(x)

[1 9 4 6 3]
[5 4 3 3 3]
[9 9 6 5 9]
[6 4 1 4 4]


In [72]:
func_row(x)

[1 5 9 6]
[9 4 9 4]
[9 4 9 4]
[6 3 5 4]
[3 3 9 4]
